[phases.setup]
nixPkgs = ["...", "ffmpeg", "nodejs", "git"]

[phases.install]
cmds = [
  "git clone --depth 1 --single-branch --branch 2.0.0 https://github.com/Brainicism/bgutil-ytdlp-pot-provider.git /app/bgutil-ytdlp-pot-provider",
  "cd /app/bgutil-ytdlp-pot-provider/server && npm ci && npx tsc",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]